Skip Pandora tests on pandas 1-
some failures related to the datetime parsing,
but I'd prefer to leave the code as-is
instead of putting in workarounds,
given that we are supporting pandas 2 officially now

FAILED tests/test_pandora.py::test_parse_metadata - AssertionError: assert False
 +  where False = isinstance('2019-01-23T00:01:03', <class 'pandas._libs.tslibs.timestamps.Timestamp'>)
 +    where '2019-01-23T00:01:03' = <function _parse_metadata at 0x7f799ff240e0>('2019-01-23T00:01:03')
 +      where <function _parse_metadata at 0x7f799ff240e0> = pandora._parse_metadata
 +    and   <class 'pandas._libs.tslibs.timestamps.Timestamp'> = pd.Timestamp
FAILED tests/test_pandora.py::test_open_dataset - ValueError: time data '20210827T204838.9Z' does not match format 'ISO8601' (match)
FAILED tests/test_pandora.py::test_open_dataset_profiles - ValueError: time data '20210827T204838.9Z' does not match format 'ISO8601' (match)
FAILED tests/test_pandora.py::test_open_mfdataset - ValueError: time data '20210827T204838.9Z' does not match format 'ISO8601' (match)